name: Build

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project repository
        uses: actions/checkout@v2
      - name: Builds with make
        run: make all
